import streamlit as st
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from pydantic import BaseModel, Field
from typing import List
import json
import re

# --- Page Configuration ---
st.set_page_config(page_title="AI Meeting Assistant", page_icon="📝")
st.title("📝 AI Meeting Assistant")
st.markdown("""
Transform raw meeting notes into structured summaries and actionable tasks.
*Powered by Google Gemini API (Free Tier)*
""")

# --- Sidebar for API Key ---
with st.sidebar:
    st.header("Settings")
    api_key = st.text_input("Google Gemini API Key", type="password")
    st.markdown("[Get your free API Key](https://aistudio.google.com/app/apikey)")
    st.info("Leave blank to use **Demo Mode** with sample data.")

# --- Data Models ---
class ActionItem(BaseModel):
    task: str = Field(description="The specific action to be taken")
    owner: str = Field(description="The person responsible for the task")
    deadline: str = Field(description="Mentioned deadline or 'Not specified'")

class MeetingSummary(BaseModel):
    summary: str = Field(description="A concise summary of the meeting")
    key_decisions: List[str] = Field(description="List of key decisions made")
    action_items: List[ActionItem] = Field(description="List of actionable tasks")

# --- Demo Data (For when no API key is provided) ---
def get_demo_data():
    return {
        "summary": "This is a demo response showing how the app structures data. In live mode, this is generated by AI.",
        "key_decisions": ["Demo Decision 1: Proceed with prototype", "Demo Decision 2: Review security policies"],
        "action_items": [
            {"task": "Update documentation", "owner": "Team", "deadline": "Next Week"},
            {"task": "Test API endpoints", "owner": "Dev Lead", "deadline": "Friday"}
        ]
    }

# --- Functions ---
def clean_json_response(text):
    """Removes markdown code blocks from the response."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    if text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def process_meeting_notes(notes, key):
    try:
        llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0, google_api_key=key)
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert meeting assistant. Analyze the provided notes and extract structured information. Output ONLY valid JSON. Do not include markdown formatting like ```json."),
            ("human", "Meeting Notes:\n{notes}"),
        ])
        chain = prompt | llm | StrOutputParser()
        response = chain.invoke({"notes": notes})
        clean_response = clean_json_response(response)
        data = json.loads(clean_response)
        return data
    except Exception as e:
        st.error(f"Processing error: {str(e)}")
        return None

# --- Main Interface ---
text_input = st.text_area("Paste Meeting Notes Here", height=200, placeholder="e.g., John agreed to update the API by Friday...")

if st.button("Generate Summary"):
    if not text_input:
        st.warning("Please enter some meeting notes.")
    else:
        with st.spinner("Analyzing notes..."):
            result = None
            if not api_key:
                # DEMO MODE
                st.info("**Demo Mode:** No API key detected. Showing sample output structure.")
                result = get_demo_data()
            else:
                # LIVE AI MODE
                result = process_meeting_notes(text_input, api_key)
            
            if result:
                st.success("Analysis Complete!")
                
                # Display Summary
                st.subheader("Summary")
                st.write(result.get("summary", "No summary available"))
                
                # Display Decisions
                st.subheader("Key Decisions")
                for decision in result.get("key_decisions", []):
                    st.write(f"- {decision}")
                
                # Display Action Items
                st.subheader("Action Items")
                for item in result.get("action_items", []):
                    with st.expander(f"Task: {item.get('task', 'Unknown Task')}"):
                        st.write(f"**Owner:** {item.get('owner', 'Unassigned')}")
                        st.write(f"**Deadline:** {item.get('deadline', 'Not specified')}")
                
                # Download Option
                st.download_button(
                    label="Download Report as JSON",
                    data=json.dumps(result, indent=2),
                    file_name="meeting_report.json",
                    mime="application/json"
                )
