import streamlit as st
import google.generativeai as genai
from pydantic import BaseModel, Field
from typing import List
import json
import re

# --- Page Configuration ---
st.set_page_config(page_title="AI Meeting Assistant", page_icon="📝")
st.title("📝 AI Meeting Assistant")
st.markdown("""
Transform raw meeting notes into structured summaries and actionable tasks.
*Powered by Google Gemini API (Free Tier)*
""")

# --- Sidebar for API Key ---
with st.sidebar:
    st.header("Settings")
    api_key = st.text_input("Google Gemini API Key", type="password")
    st.markdown("[Get your free API Key](https://aistudio.google.com/app/apikey)")
    st.info("Leave blank to use **Demo Mode** with sample data.")

# --- Data Models ---
class ActionItem(BaseModel):
    task: str = Field(description="The specific action to be taken")
    owner: str = Field(description="The person responsible for the task")
    deadline: str = Field(description="Mentioned deadline or 'Not specified'")

class MeetingSummary(BaseModel):
    summary: str = Field(description="A concise summary of the meeting")
    key_decisions: List[str] = Field(description="List of key decisions made")
    action_items: List[ActionItem] = Field(description="List of actionable tasks")

# --- Demo Data (For when no API key is provided) ---
def get_demo_data():
    return {
        "summary": "This is a demo response showing how the app structures data. In live mode, this is generated by AI.",
        "key_decisions": ["Demo Decision 1: Proceed with prototype", "Demo Decision 2: Review security policies"],
        "action_items": [
            {"task": "Update documentation", "owner": "Team", "deadline": "Next Week"},
            {"task": "Test API endpoints", "owner": "Dev Lead", "deadline": "Friday"}
        ]
    }

# --- Functions ---
def clean_json_response(text):
    """Removes markdown code blocks from the response."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def process_meeting_notes(notes, key):
    try:
        # Configure the native SDK
        genai.configure(api_key=key)
        
        # Force JSON output using generation_config
        model = genai.GenerativeModel(
            'gemini-1.5-flash',
            generation_config={"response_mime_type": "application/json"}
        )
        
        # Prompt engineering for structured JSON
        prompt = f"""
        You are an expert meeting assistant. Analyze the following meeting notes and extract structured information.
        
        Meeting Notes:
        {notes}
        
        Required JSON Structure:
        {{
            "summary": "string",
            "key_decisions": ["string", "string"],
            "action_items": [
                {{"task": "string", "owner": "string", "deadline": "string"}}
            ]
        }}
        """
        
        # Generate Content
        response = model.generate_content(prompt)
        
        # Because we used response_mime_type, the output is guaranteed to be a valid JSON string.
        # No manual cleaning needed!
        data = json.loads(response.text)
        return data

    except Exception as e:
        # Improved error logging to help you debug in Streamlit
        st.error(f"Processing error: {str(e)}")
        st.info("Check if your API key is valid and has sufficient quota.")
        return None

# --- Main Interface ---
text_input = st.text_area("Paste Meeting Notes Here", height=200, placeholder="e.g., John agreed to update the API by Friday...")

if st.button("Generate Summary"):
    if not text_input:
        st.warning("Please enter some meeting notes.")
    else:
        with st.spinner("Analyzing notes..."):
            result = None
            if not api_key:
                # DEMO MODE
                st.info("🚀 **Demo Mode:** No API key detected. Showing sample output structure.")
                result = get_demo_data()
            else:
                # LIVE AI MODE
                result = process_meeting_notes(text_input, api_key)
            
            if result:
                st.success("Analysis Complete!")
                
                # Display Summary
                st.subheader("📄 Summary")
                st.write(result.get("summary", "No summary available"))
                
                # Display Decisions
                st.subheader("🔑 Key Decisions")
                for decision in result.get("key_decisions", []):
                    st.write(f"- {decision}")
                
                # Display Action Items
                st.subheader("✅ Action Items")
                for item in result.get("action_items", []):
                    with st.expander(f"Task: {item.get('task', 'Unknown Task')}"):
                        st.write(f"**Owner:** {item.get('owner', 'Unassigned')}")
                        st.write(f"**Deadline:** {item.get('deadline', 'Not specified')}")
                
                # Download Option
                st.download_button(
                    label="Download Report as JSON",
                    data=json.dumps(result, indent=2),
                    file_name="meeting_report.json",
                    mime="application/json"
                )
